Create FRP-37.md
flashbots/mev-research pull request #113
Opened 2023-09-03 03:45 UTC by WudingRoad1145

Proposing a new FRP after talks with Xyn over last week :D

2023-09-06 06:22 UTC, sxysun commented
looks interesting, I would suggest this FRP to target answering the following two questions:
- measure the cooperation/coordination ability of LLM agents when they are given access to smart contracts, specifically, I would like to see comparison between their cooperation ability when they are given no contracts v.s. when they are given the ability to use credible commitments: **I'd be curious to see how well those agents could write and read/understand smart contracts and the implication to their game play, i.e., how strong is their "theory of mind" reasoning.** Some followups could be: how can we use chain-of-thought or reinforcement learning to strengthen those agents to make their coordination more robust.
- measure how well does this ability of using smart contracts to coordination for LLM agents transfer across different games/how robust it is when other agents are not controlled by LLM but are strategic agents capable of adversarial/exploitative behavior, like **I would suspect that in real situations, prompt-injection attacks embedded in the contracts would prove to be difficult for the agents to deal with. I'd like to see a characterization of the efficacy of such attacks and the mitigation techniques.**

2023-09-12 08:52 UTC, WudingRoad1145 commented
@sxysun  Thanks for the great insight! We have updated our research proposal accordingly.

2023-09-15 15:37 UTC, sarahalle requested changes
Please edit according to the submission template instructions- rename the file to the project name not an FRP number, remove the id number from the header, and remove the status. These are all assigned upon acceptance, and the ones you added are out of date

2023-09-16 02:42 UTC, WudingRoad1145 commented
Hi Sarah! Thank you for taking the time to review our proposal. I have made the necessary updates to the file in accordance with the submission template. Super excited!

2023-09-20 20:13 UTC, merged